-- Programme réel de la Convention Paris 2026 (24–26 juillet), transcrit du
-- planning d'origine. Horaires et intitulés repris tels quels.
--
-- À coller dans Supabase ▸ SQL Editor. Écrase la section « sessions » du
-- contenu ; les journées 4 à 8 restent à compléter depuis /admin.
--
-- Réexécutable sans risque. Pour revenir en arrière, réécrivez la section
-- depuis /admin : cette table est la source de vérité de l'application.

update public.content
   set data = '[
  {
    "id": "d1s1",
    "dayId": "d1",
    "startISO": "2026-07-24T14:35+02:00",
    "endISO": "2026-07-24T16:00+02:00",
    "tFr": "Mise en place et installation des invités",
    "tEn": "Setup and seating of guests",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d1s2",
    "dayId": "d1",
    "startISO": "2026-07-24T16:00+02:00",
    "endISO": "2026-07-24T16:03+02:00",
    "tFr": "Animation communication • Prière d''ouverture",
    "tEn": "Announcements • Opening prayer",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d1s3",
    "dayId": "d1",
    "startISO": "2026-07-24T16:03+02:00",
    "endISO": "2026-07-24T16:06+02:00",
    "tFr": "Prière pour la nation",
    "tEn": "Prayer for the nation",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d1s4",
    "dayId": "d1",
    "startISO": "2026-07-24T16:06+02:00",
    "endISO": "2026-07-24T16:09+02:00",
    "tFr": "Prière pour les autorités administratives",
    "tEn": "Prayer for the civil authorities",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d1s5",
    "dayId": "d1",
    "startISO": "2026-07-24T16:09+02:00",
    "endISO": "2026-07-24T16:12+02:00",
    "tFr": "Prière pour les autorités religieuses",
    "tEn": "Prayer for the religious authorities",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d1s6",
    "dayId": "d1",
    "startISO": "2026-07-24T16:12+02:00",
    "endISO": "2026-07-24T16:15+02:00",
    "tFr": "Prière pour la propagation de l''Évangile",
    "tEn": "Prayer for the spread of the Gospel",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d1s7",
    "dayId": "d1",
    "startISO": "2026-07-24T16:15+02:00",
    "endISO": "2026-07-24T16:20+02:00",
    "tFr": "Lecture de l''autorisation de manifestation publique",
    "tEn": "Reading of the public gathering authorisation",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d1s8",
    "dayId": "d1",
    "startISO": "2026-07-24T16:20+02:00",
    "endISO": "2026-07-24T16:25+02:00",
    "tFr": "Exécution de l''hymne national de la France",
    "tEn": "French national anthem",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "ceremonie"
  },
  {
    "id": "d1s9",
    "dayId": "d1",
    "startISO": "2026-07-24T16:25+02:00",
    "endISO": "2026-07-24T16:35+02:00",
    "tFr": "Communication élément 1",
    "tEn": "Announcements, part 1",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d1s10",
    "dayId": "d1",
    "startISO": "2026-07-24T16:35+02:00",
    "endISO": "2026-07-24T16:45+02:00",
    "tFr": "Mot de bienvenue du coordonnateur de la diaspora",
    "tEn": "Welcome address by the diaspora coordinator",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "ceremonie"
  },
  {
    "id": "d1s11",
    "dayId": "d1",
    "startISO": "2026-07-24T16:45+02:00",
    "endISO": "2026-07-24T16:55+02:00",
    "tFr": "Communication élément 2",
    "tEn": "Announcements, part 2",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d1s12",
    "dayId": "d1",
    "startISO": "2026-07-24T17:00+02:00",
    "endISO": "2026-07-24T18:00+02:00",
    "tFr": "Cérémonie d''ouverture",
    "tEn": "Opening ceremony",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "ceremonie"
  },
  {
    "id": "d1s13",
    "dayId": "d1",
    "startISO": "2026-07-24T18:00+02:00",
    "endISO": "2026-07-24T18:15+02:00",
    "tFr": "Présentation des délégations présentes",
    "tEn": "Presentation of the delegations",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "ceremonie"
  },
  {
    "id": "d1s14",
    "dayId": "d1",
    "startISO": "2026-07-24T18:15+02:00",
    "endISO": "2026-07-24T18:20+02:00",
    "tFr": "Ouverture officielle de la convention par le PA",
    "tEn": "Official opening of the convention by the PA",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "ceremonie"
  },
  {
    "id": "d1s15",
    "dayId": "d1",
    "startISO": "2026-07-24T18:20+02:00",
    "endISO": "2026-07-24T20:00+02:00",
    "tFr": "Prédication inaugurale",
    "tEn": "Inaugural preaching",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "enseignement"
  },
  {
    "id": "d1s16",
    "dayId": "d1",
    "startISO": "2026-07-24T20:00+02:00",
    "endISO": "2026-07-24T20:30+02:00",
    "tFr": "Informations générales et prière de clôture",
    "tEn": "General information and closing prayer",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d1s17",
    "dayId": "d1",
    "startISO": "2026-07-24T20:30+02:00",
    "endISO": "2026-07-24T21:15+02:00",
    "tFr": "Repas (dîner)",
    "tEn": "Dinner",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "pause"
  },
  {
    "id": "d2s1",
    "dayId": "d2",
    "startISO": "2026-07-25T07:00+02:00",
    "endISO": "2026-07-25T08:30+02:00",
    "tFr": "Petit-déjeuner",
    "tEn": "Breakfast",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "pause"
  },
  {
    "id": "d2s2",
    "dayId": "d2",
    "startISO": "2026-07-25T08:30+02:00",
    "endISO": "2026-07-25T11:30+02:00",
    "tFr": "L''urgence de la convocation : les jugements exercés dans le passé",
    "tEn": "The urgency of the call: judgements of the past",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "enseignement"
  },
  {
    "id": "d2s3",
    "dayId": "d2",
    "startISO": "2026-07-25T11:30+02:00",
    "endISO": "2026-07-25T12:00+02:00",
    "tFr": "Pause + déjeuner",
    "tEn": "Break and lunch",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "pause"
  },
  {
    "id": "d2s4",
    "dayId": "d2",
    "startISO": "2026-07-25T12:00+02:00",
    "endISO": "2026-07-25T15:00+02:00",
    "tFr": "Les origines de la mort • Le sort du témoin",
    "tEn": "The origins of death • The fate of the witness",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "enseignement"
  },
  {
    "id": "d2s5",
    "dayId": "d2",
    "startISO": "2026-07-25T15:00+02:00",
    "endISO": "2026-07-25T16:00+02:00",
    "tFr": "La destination des morts",
    "tEn": "The destination of the dead",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "enseignement"
  },
  {
    "id": "d2s6",
    "dayId": "d2",
    "startISO": "2026-07-25T16:30+02:00",
    "endISO": "2026-07-25T19:00+02:00",
    "tFr": "De la mort à la vie",
    "tEn": "From death to life",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "enseignement"
  },
  {
    "id": "d2s7",
    "dayId": "d2",
    "startISO": "2026-07-25T19:00+02:00",
    "endISO": "2026-07-25T20:00+02:00",
    "tFr": "Dîner",
    "tEn": "Dinner",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "pause"
  },
  {
    "id": "d3s1",
    "dayId": "d3",
    "startISO": "2026-07-26T07:15+02:00",
    "endISO": "2026-07-26T08:15+02:00",
    "tFr": "Petit-déjeuner",
    "tEn": "Breakfast",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "pause"
  },
  {
    "id": "d3s2",
    "dayId": "d3",
    "startISO": "2026-07-26T08:00+02:00",
    "endISO": "2026-07-26T08:30+02:00",
    "tFr": "Installation des matériels et mise en place des différents ministères",
    "tEn": "Equipment setup and ministry teams in place",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d3s3",
    "dayId": "d3",
    "startISO": "2026-07-26T08:30+02:00",
    "endISO": "2026-07-26T09:00+02:00",
    "tFr": "Accueil des participants et animations",
    "tEn": "Welcome of participants and activities",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d3s4",
    "dayId": "d3",
    "startISO": "2026-07-26T09:00+02:00",
    "endISO": "2026-07-26T09:05+02:00",
    "tFr": "Début du culte",
    "tEn": "Start of the service",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "culte"
  },
  {
    "id": "d3s5",
    "dayId": "d3",
    "startISO": "2026-07-26T09:05+02:00",
    "endISO": "2026-07-26T09:15+02:00",
    "tFr": "Sujet prière",
    "tEn": "Prayer topic",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d3s6",
    "dayId": "d3",
    "startISO": "2026-07-26T09:15+02:00",
    "endISO": "2026-07-26T09:25+02:00",
    "tFr": "Cantiques",
    "tEn": "Hymns",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "louange"
  },
  {
    "id": "d3s7",
    "dayId": "d3",
    "startISO": "2026-07-26T09:25+02:00",
    "endISO": "2026-07-26T09:50+02:00",
    "tFr": "Témoignages d''hier",
    "tEn": "Yesterday''s testimonies",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "culte"
  },
  {
    "id": "d3s8",
    "dayId": "d3",
    "startISO": "2026-07-26T09:50+02:00",
    "endISO": "2026-07-26T10:15+02:00",
    "tFr": "Prestation des plus petits",
    "tEn": "Children''s performance",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "culte"
  },
  {
    "id": "d3s9",
    "dayId": "d3",
    "startISO": "2026-07-26T10:15+02:00",
    "endISO": "2026-07-26T10:25+02:00",
    "tFr": "Communication",
    "tEn": "Announcements",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d3s10",
    "dayId": "d3",
    "startISO": "2026-07-26T10:55+02:00",
    "endISO": "2026-07-26T11:10+02:00",
    "tFr": "Louanges",
    "tEn": "Praise",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "louange"
  },
  {
    "id": "d3s11",
    "dayId": "d3",
    "startISO": "2026-07-26T11:10+02:00",
    "endISO": "2026-07-26T13:00+02:00",
    "tFr": "Sermon",
    "tEn": "Sermon",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "enseignement"
  },
  {
    "id": "d3s12",
    "dayId": "d3",
    "startISO": "2026-07-26T13:00+02:00",
    "endISO": "2026-07-26T13:10+02:00",
    "tFr": "Informations générales et prière de clôture",
    "tEn": "General information and closing prayer",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d3s13",
    "dayId": "d3",
    "startISO": "2026-07-26T13:15+02:00",
    "endISO": "2026-07-26T14:15+02:00",
    "tFr": "Mini concert",
    "tEn": "Mini concert",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "louange"
  },
  {
    "id": "d3s14",
    "dayId": "d3",
    "startISO": "2026-07-26T14:20+02:00",
    "endISO": "2026-07-26T15:00+02:00",
    "tFr": "Déjeuner",
    "tEn": "Lunch",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "pause"
  }
]'::jsonb,
       updated_at = now()
 where section = 'sessions';

-- Si la ligne n'existait pas encore (base jamais amorcée) :
insert into public.content (section, data)
select 'sessions', '[
  {
    "id": "d1s1",
    "dayId": "d1",
    "startISO": "2026-07-24T14:35+02:00",
    "endISO": "2026-07-24T16:00+02:00",
    "tFr": "Mise en place et installation des invités",
    "tEn": "Setup and seating of guests",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d1s2",
    "dayId": "d1",
    "startISO": "2026-07-24T16:00+02:00",
    "endISO": "2026-07-24T16:03+02:00",
    "tFr": "Animation communication • Prière d''ouverture",
    "tEn": "Announcements • Opening prayer",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d1s3",
    "dayId": "d1",
    "startISO": "2026-07-24T16:03+02:00",
    "endISO": "2026-07-24T16:06+02:00",
    "tFr": "Prière pour la nation",
    "tEn": "Prayer for the nation",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d1s4",
    "dayId": "d1",
    "startISO": "2026-07-24T16:06+02:00",
    "endISO": "2026-07-24T16:09+02:00",
    "tFr": "Prière pour les autorités administratives",
    "tEn": "Prayer for the civil authorities",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d1s5",
    "dayId": "d1",
    "startISO": "2026-07-24T16:09+02:00",
    "endISO": "2026-07-24T16:12+02:00",
    "tFr": "Prière pour les autorités religieuses",
    "tEn": "Prayer for the religious authorities",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d1s6",
    "dayId": "d1",
    "startISO": "2026-07-24T16:12+02:00",
    "endISO": "2026-07-24T16:15+02:00",
    "tFr": "Prière pour la propagation de l''Évangile",
    "tEn": "Prayer for the spread of the Gospel",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d1s7",
    "dayId": "d1",
    "startISO": "2026-07-24T16:15+02:00",
    "endISO": "2026-07-24T16:20+02:00",
    "tFr": "Lecture de l''autorisation de manifestation publique",
    "tEn": "Reading of the public gathering authorisation",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d1s8",
    "dayId": "d1",
    "startISO": "2026-07-24T16:20+02:00",
    "endISO": "2026-07-24T16:25+02:00",
    "tFr": "Exécution de l''hymne national de la France",
    "tEn": "French national anthem",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "ceremonie"
  },
  {
    "id": "d1s9",
    "dayId": "d1",
    "startISO": "2026-07-24T16:25+02:00",
    "endISO": "2026-07-24T16:35+02:00",
    "tFr": "Communication élément 1",
    "tEn": "Announcements, part 1",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d1s10",
    "dayId": "d1",
    "startISO": "2026-07-24T16:35+02:00",
    "endISO": "2026-07-24T16:45+02:00",
    "tFr": "Mot de bienvenue du coordonnateur de la diaspora",
    "tEn": "Welcome address by the diaspora coordinator",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "ceremonie"
  },
  {
    "id": "d1s11",
    "dayId": "d1",
    "startISO": "2026-07-24T16:45+02:00",
    "endISO": "2026-07-24T16:55+02:00",
    "tFr": "Communication élément 2",
    "tEn": "Announcements, part 2",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d1s12",
    "dayId": "d1",
    "startISO": "2026-07-24T17:00+02:00",
    "endISO": "2026-07-24T18:00+02:00",
    "tFr": "Cérémonie d''ouverture",
    "tEn": "Opening ceremony",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "ceremonie"
  },
  {
    "id": "d1s13",
    "dayId": "d1",
    "startISO": "2026-07-24T18:00+02:00",
    "endISO": "2026-07-24T18:15+02:00",
    "tFr": "Présentation des délégations présentes",
    "tEn": "Presentation of the delegations",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "ceremonie"
  },
  {
    "id": "d1s14",
    "dayId": "d1",
    "startISO": "2026-07-24T18:15+02:00",
    "endISO": "2026-07-24T18:20+02:00",
    "tFr": "Ouverture officielle de la convention par le PA",
    "tEn": "Official opening of the convention by the PA",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "ceremonie"
  },
  {
    "id": "d1s15",
    "dayId": "d1",
    "startISO": "2026-07-24T18:20+02:00",
    "endISO": "2026-07-24T20:00+02:00",
    "tFr": "Prédication inaugurale",
    "tEn": "Inaugural preaching",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "enseignement"
  },
  {
    "id": "d1s16",
    "dayId": "d1",
    "startISO": "2026-07-24T20:00+02:00",
    "endISO": "2026-07-24T20:30+02:00",
    "tFr": "Informations générales et prière de clôture",
    "tEn": "General information and closing prayer",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d1s17",
    "dayId": "d1",
    "startISO": "2026-07-24T20:30+02:00",
    "endISO": "2026-07-24T21:15+02:00",
    "tFr": "Repas (dîner)",
    "tEn": "Dinner",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "pause"
  },
  {
    "id": "d2s1",
    "dayId": "d2",
    "startISO": "2026-07-25T07:00+02:00",
    "endISO": "2026-07-25T08:30+02:00",
    "tFr": "Petit-déjeuner",
    "tEn": "Breakfast",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "pause"
  },
  {
    "id": "d2s2",
    "dayId": "d2",
    "startISO": "2026-07-25T08:30+02:00",
    "endISO": "2026-07-25T11:30+02:00",
    "tFr": "L''urgence de la convocation : les jugements exercés dans le passé",
    "tEn": "The urgency of the call: judgements of the past",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "enseignement"
  },
  {
    "id": "d2s3",
    "dayId": "d2",
    "startISO": "2026-07-25T11:30+02:00",
    "endISO": "2026-07-25T12:00+02:00",
    "tFr": "Pause + déjeuner",
    "tEn": "Break and lunch",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "pause"
  },
  {
    "id": "d2s4",
    "dayId": "d2",
    "startISO": "2026-07-25T12:00+02:00",
    "endISO": "2026-07-25T15:00+02:00",
    "tFr": "Les origines de la mort • Le sort du témoin",
    "tEn": "The origins of death • The fate of the witness",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "enseignement"
  },
  {
    "id": "d2s5",
    "dayId": "d2",
    "startISO": "2026-07-25T15:00+02:00",
    "endISO": "2026-07-25T16:00+02:00",
    "tFr": "La destination des morts",
    "tEn": "The destination of the dead",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "enseignement"
  },
  {
    "id": "d2s6",
    "dayId": "d2",
    "startISO": "2026-07-25T16:30+02:00",
    "endISO": "2026-07-25T19:00+02:00",
    "tFr": "De la mort à la vie",
    "tEn": "From death to life",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "enseignement"
  },
  {
    "id": "d2s7",
    "dayId": "d2",
    "startISO": "2026-07-25T19:00+02:00",
    "endISO": "2026-07-25T20:00+02:00",
    "tFr": "Dîner",
    "tEn": "Dinner",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "pause"
  },
  {
    "id": "d3s1",
    "dayId": "d3",
    "startISO": "2026-07-26T07:15+02:00",
    "endISO": "2026-07-26T08:15+02:00",
    "tFr": "Petit-déjeuner",
    "tEn": "Breakfast",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "pause"
  },
  {
    "id": "d3s2",
    "dayId": "d3",
    "startISO": "2026-07-26T08:00+02:00",
    "endISO": "2026-07-26T08:30+02:00",
    "tFr": "Installation des matériels et mise en place des différents ministères",
    "tEn": "Equipment setup and ministry teams in place",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d3s3",
    "dayId": "d3",
    "startISO": "2026-07-26T08:30+02:00",
    "endISO": "2026-07-26T09:00+02:00",
    "tFr": "Accueil des participants et animations",
    "tEn": "Welcome of participants and activities",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d3s4",
    "dayId": "d3",
    "startISO": "2026-07-26T09:00+02:00",
    "endISO": "2026-07-26T09:05+02:00",
    "tFr": "Début du culte",
    "tEn": "Start of the service",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "culte"
  },
  {
    "id": "d3s5",
    "dayId": "d3",
    "startISO": "2026-07-26T09:05+02:00",
    "endISO": "2026-07-26T09:15+02:00",
    "tFr": "Sujet prière",
    "tEn": "Prayer topic",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d3s6",
    "dayId": "d3",
    "startISO": "2026-07-26T09:15+02:00",
    "endISO": "2026-07-26T09:25+02:00",
    "tFr": "Cantiques",
    "tEn": "Hymns",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "louange"
  },
  {
    "id": "d3s7",
    "dayId": "d3",
    "startISO": "2026-07-26T09:25+02:00",
    "endISO": "2026-07-26T09:50+02:00",
    "tFr": "Témoignages d''hier",
    "tEn": "Yesterday''s testimonies",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "culte"
  },
  {
    "id": "d3s8",
    "dayId": "d3",
    "startISO": "2026-07-26T09:50+02:00",
    "endISO": "2026-07-26T10:15+02:00",
    "tFr": "Prestation des plus petits",
    "tEn": "Children''s performance",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "culte"
  },
  {
    "id": "d3s9",
    "dayId": "d3",
    "startISO": "2026-07-26T10:15+02:00",
    "endISO": "2026-07-26T10:25+02:00",
    "tFr": "Communication",
    "tEn": "Announcements",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "accueil"
  },
  {
    "id": "d3s10",
    "dayId": "d3",
    "startISO": "2026-07-26T10:55+02:00",
    "endISO": "2026-07-26T11:10+02:00",
    "tFr": "Louanges",
    "tEn": "Praise",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "louange"
  },
  {
    "id": "d3s11",
    "dayId": "d3",
    "startISO": "2026-07-26T11:10+02:00",
    "endISO": "2026-07-26T13:00+02:00",
    "tFr": "Sermon",
    "tEn": "Sermon",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "enseignement"
  },
  {
    "id": "d3s12",
    "dayId": "d3",
    "startISO": "2026-07-26T13:00+02:00",
    "endISO": "2026-07-26T13:10+02:00",
    "tFr": "Informations générales et prière de clôture",
    "tEn": "General information and closing prayer",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "priere"
  },
  {
    "id": "d3s13",
    "dayId": "d3",
    "startISO": "2026-07-26T13:15+02:00",
    "endISO": "2026-07-26T14:15+02:00",
    "tFr": "Mini concert",
    "tEn": "Mini concert",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "louange"
  },
  {
    "id": "d3s14",
    "dayId": "d3",
    "startISO": "2026-07-26T14:20+02:00",
    "endISO": "2026-07-26T15:00+02:00",
    "tFr": "Déjeuner",
    "tEn": "Lunch",
    "spFr": "",
    "spEn": "",
    "locFr": "Amphithéâtre Novotel, Charenton-le-Pont",
    "locEn": "Novotel Amphitheatre, Charenton-le-Pont",
    "tag": "pause"
  }
]'::jsonb
 where not exists (select 1 from public.content where section = 'sessions');

-- Contrôle : doit renvoyer 38 sessions réparties sur d1, d2 et d3.
select jsonb_array_length(data) as nb_sessions from public.content where section = 'sessions';
